services:
  - type: web
    name: ecole-des-maris
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true
    branch: main
